### PR TITLE
Create maven.yml

### LINKED ISSUE #12: Provide a Github verification action
As part of https://github.com/faktorips/faktorips.base/issues/8 it was noticed that there is currently no [Actions](https://github.com/faktorips/faktorips.base/actions) configured to build the repository and verify code changes.

### PR DESCRIPTION
**Pull request by laeubi**
This will fix #12 by providing a github verification action

### CODE REVIEW

**Comment by laeubi** [comment]
This requires #25 and #24 to succeed.

**Comment by laeubi** [comment]
This is now ready to be merged.

**Review by hd42 — APPROVED** [review]

**Comment by hd42** [comment]
Merged as https://github.com/faktorips/faktorips.base/commit/bfe2331fef5fdcc73cf0d33945d4674dc847e602

**Comment by laeubi** [comment]
Great, the workflow has already run successful:
 https://github.com/faktorips/faktorips.base/actions

**Pull request closed without merging**
