### PR TITLE
Update maven.yml

### PR DESCRIPTION
**Pull request by laeubi**
Use 'verify' to also execute tests!

### CODE REVIEW

**Comment by laeubi** [comment]
This should execute the tests and publish the results ...

**Comment by laeubi** [comment]
Running tests for all eclipse versions seem to produce heavy load (and ghaction resource might be limited for free plans) would it be suitable to run the tests only for a certain platform configuration?

**Comment by hd42** [comment]
> Running tests for all eclipse versions seem to produce heavy load (and ghaction resource might be limited for free plans) would it be suitable to run the tests only for a certain platform configuration?

Yes. It should be enough to **build** against all targets (to detect incompatible API changes) but only run the tests against 2019-03. We currently use a matrix test that runs daily and tests the code compiled against 2019-03 against all targets. Testing code compiled against another target is probably useless, as nobody compiles Faktor-IPS against their own target and we release the build against 2019-03, our current minimal requirement.

**Comment by laeubi** [comment]
@hd42 finally everything works now as desired. The check that all unit tests passes will only be active once merged into the repository for the first time, but you can download the test results here and investigate if everything is included:
https://github.com/faktorips/faktorips.base/suites/5589599239/artifacts/181229255

**Comment by laeubi** [comment]
@hd42 do you think anything is left here or can we merge it?

**Comment by hd42** [comment]
Merged as https://github.com/faktorips/faktorips.base/commit/6a60d032f14de03b11527e8ded14371c3ab7da04

**Pull request closed without merging**
